apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: {{.Release.Namespace}}
data:
  fluent-bit.yaml: |
    pipeline:
      inputs:
        - name: tail
          path: /data/audit/modsec.log
      outputs:
        - name: stdout
          match: "*"
