apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wafie-control-plane
  namespace: {{.Release.Namespace}}
spec:
  rules:
    - host: wafie-api.10.100.102.84.nip.io
      http:
        paths:
          - backend:
              service:
                name: wafie-control-plane
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific