apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wafy
  namespace: {{.Release.Namespace}}
spec:
  rules:
    - host: wafy-api.10.100.102.84.nip.io
      http:
        paths:
          - backend:
              service:
                name: wafy
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific