apiVersion: v1
kind: ServiceAccount
metadata:
  name: wafie-control-plane
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wafie-control-plane
rules:
  - apiGroups: [ "" ]
    resources: [ "services"]
    verbs: [ "get", "list"]
  - apiGroups: [ "" ]
    resources: [ "pods"]
    verbs: [ "get", "list"]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices"]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get","list","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wafie-control-plane
subjects:
  - kind: ServiceAccount
    name: wafie-control-plane
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: wafie-control-plane
  apiGroup: rbac.authorization.k8s.io