apiVersion: v1
kind: ServiceAccount
metadata:
  name: wafy
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wafy
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "update" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "create","get","list","update","watch","delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wafy
subjects:
  - kind: ServiceAccount
    name: wafy
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: wafy
  apiGroup: rbac.authorization.k8s.io