apiVersion: v1
kind: Service
metadata:
  name: wafy-api-server
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: wafy-api-server
  ports:
    - name: http
      port: 8080
      targetPort: api-server
    - name: grpc
      port: 18000
      targetPort: pcp