apiVersion: v1
kind: Service
metadata:
  name: wafy-core
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: wafy-core
  ports:
    - name: api-http
      port: 8080
      targetPort: api-server
    - name: grpc
      port: 18000
      targetPort: pcp
    - name: waf-http
      port: 8888
      targetPort: waf