#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: wafie-devpod-data
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wafie-devpod
  labels:
    app: wafie-devpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wafie-devpod
  template:
    metadata:
      labels:
        app: wafie-devpod
    spec:
      hostNetwork: true
      serviceAccountName: wafie-control-plane
      containers:
        - name: wafie-devpod
          command:
            - /bin/bash
            - -c
            - /usr/bin/sshd -D
          image: dimssss/wafie-devpod
          imagePullPolicy: Always
          ports:
            - name: ssh
              containerPort: 22
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
          volumeMounts:
            - name: netns
              mountPath: /var/run/netns
              readOnly: true
            - name: data
              mountPath: /root/.go/src/github.com
      volumes:
        - name: netns
          hostPath:
            path: /var/run/netns
        - name: data
          persistentVolumeClaim:
            claimName: wafie-devpod-data
