apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cwaf-console
spec:
  rules:
    - host: cwaf-console.172.20.10.5.nip.io
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /
            backend:
              service:
                name: cwaf-test-1
                port:
                  number: 80
