apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: wp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/version: 6.7.2
    helm.sh/chart: wordpress-24.2.2
  name: wp-wordpress
  namespace: default
spec:
  ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: http
      - name: https
        port: 443
        protocol: TCP
        targetPort: https
  selector:
    app: cwaf-test
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app.kubernetes.io/instance: wp
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/name: wordpress
#    app.kubernetes.io/version: 6.7.2
#    helm.sh/chart: wordpress-24.2.2
#  name: wp-wordpress-cwaf-protected
#  namespace: default
#spec:
#  ports:
#    - name: http
#      port: 80
#      protocol: TCP
#      targetPort: http
#    - name: https
#      port: 443
#      protocol: TCP
#      targetPort: https
#  selector:
#    app.kubernetes.io/instance: wp
#    app.kubernetes.io/name: wordpress
#  type: ClusterIP
#
#
