FROM envoyproxy/envoy:contrib-v1.34.1 AS modsecfilter-builder
ENV GO_VERSION="https://go.dev/dl/go1.24.4.linux-arm64.tar.gz"
ENV GOBIN="/go/bin"
ENV PATH="${PATH}:${GOBIN}:/usr/local/go/bin"
ENV GOPATH="/go"
WORKDIR /go/src
RUN apt -y update \
    && apt -y install \
      libxml2-dev \
      libyajl-dev \
      libgeoip-dev \
      libcurl4-openssl-dev \
      gcc \
      vim \
      wget
RUN wget $GO_VERSION \
    && tar -C /usr/local -xzf go1.24.4.linux-arm64.tar.gz \
    && rm go1.24.4.linux-arm64.tar.gz \
    && mkdir -p /go/bin \
    && go install github.com/go-delve/delve/cmd/dlv@latest
COPY cmd/modsecfilter/include/ /usr/local/include/
COPY cmd/modsecfilter/libkubeguard.so /usr/local/lib/libkubeguard.so
ADD go.mod go.sum ./
ADD cmd/modsecfilter ./cmd/modsecfilter/
ADD internal/applogger ./internal/applogger/
RUN go build -ldflags='-s -w' -o ./kubeguard-modsec.so -buildmode=c-shared ./cmd/modsecfilter

FROM envoyproxy/envoy:contrib-v1.34.1
RUN apt -y update \
    && apt -y install \
      libxml2-dev \
      libyajl-dev \
      libgeoip-dev \
      libcurl4-openssl-dev \
      gcc \
      vim \
      wget
COPY cmd/modsecfilter/config/ /config/
COPY cmd/modsecfilter/include/ /usr/local/include/
COPY cmd/modsecfilter/libkubeguard.so /usr/local/lib/libkubeguard.so
COPY --from=modsecfilter-builder /go/src/kubeguard-modsec.so /usr/local/lib/kubeguard-modsec.so
COPY ops/envoy/ /etc/envoy/
RUN ldconfig