apiVersion: v1
kind: Pod
metadata:
  name: devpod-default
  namespace: default
spec:
  hostPID: true
  containers:
    - args:
        - -c
        - |-
          echo Container started
          trap "exit 0" 15
          
          exec "$@"
          while sleep 1 & wait $!; do :; done
        - '-'
      command:
        - /bin/sh
      env:
        - name: DEVPOD
          value: "true"
        - name: REMOTE_CONTAINERS
          value: "true"
      image: docker.io/dimssss/ebpf-dev
      imagePullPolicy: Always
      name: devpod
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]  # Only what's needed
      volumeMounts:
        - name: cri-socket
          mountPath: /run/containerd
        - name: procfs
          mountPath: /host/proc
        - name: netns
          mountPath: /host/var/run/netns
  serviceAccountName: wafie-control-plane
  volumes:
    - name: cri-socket
      hostPath:
        path: /run/containerd
    - name: procfs
      hostPath:
        path: /proc
    - name: netns
      hostPath:
        path: /var/run/netns

