kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wafie-api-docker-build
  namespace: default
spec:
  output:
    to:
      kind: DockerImage
      name: 'docker.io/dimssss/wafie-control-plane:latest'
    pushSecret:
      name: regcred
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile_wafie_control_plane
  source:
    type: Git
    git:
      uri: 'https://github.com/Dimss/wafie'