kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wafie-api-docker-build
  namespace: default
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'wafie-control-plane:latest'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile_wafie_control_plane
  source:
    type: Git
    git:
      uri: 'https://github.com/Dimss/wafie'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: wafie-control-plane
  namespace: default
