kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wafie-gateway
  namespace: default
spec:
  output:
    to:
      kind: DockerImage
      name: 'docker.io/dimssss/wafie-gateway:latest'
    pushSecret:
      name: regcred
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: dockerfiles/Dockerfile_wafie_gateway
  source:
    type: Git
    git:
      uri: 'https://github.com/Dimss/wafie'